# id
server_id = ""

# name
server_name = ""

# w3c ip
server_w3c_ip = ""

# local ip
server_local_ip = ""

# grpc server port
server_grpc_port = 40600

# working server port
server_working_port = 30600
