[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.12.3"
prost = "0.13.5"
prost-types = { version = "0.13.5", optional = true }

[build-dependencies]
prost-build = "0.13.5"
tonic-build = "0.12.3"