# name
server_name = "Srv.Profile.01"

# w3c ip
server_w3c_ip = "127.0.0.1"

# local ip
server_local_ip = "127.0.0.1"

# grpc server port
server_grpc_port = 40700

# working server port
server_working_port = 30700

# spvr server ip
spvr_server_ip = "127.0.0.1"

# spvr server port
spvr_server_port = 30500