// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpvrRelayHello {
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub server_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub server_w3c_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub server_local_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub server_grpc_port: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub server_working_port: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpvrRelayHeartBeat {
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub hb_index: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpvrRelayMessage {
    #[prost(enumeration = "SpvrRelayType", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "5")]
    pub hello: ::core::option::Option<SpvrRelayHello>,
    #[prost(message, optional, tag = "10")]
    pub heartbeat: ::core::option::Option<SpvrRelayHeartBeat>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpvrRelayType {
    KSpvrRelayHello = 0,
    KSpvrRelayHeartBeat = 1,
}
impl SpvrRelayType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::KSpvrRelayHello => "kSpvrRelayHello",
            Self::KSpvrRelayHeartBeat => "kSpvrRelayHeartBeat",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "kSpvrRelayHello" => Some(Self::KSpvrRelayHello),
            "kSpvrRelayHeartBeat" => Some(Self::KSpvrRelayHeartBeat),
            _ => None,
        }
    }
}
